### ISSUE TITLE
Can't load characters into AI Character Editor

### ISSUE THREAD

**Issue by evangineer** [mbchang/data-driven-characters#4]
I tried loading both `Thor.json` and `Evelyn.json`.

https://zoltanai.github.io/character-editor/

**Comment by mbchang** [comment]
My understanding is that https://zoltanai.github.io/character-editor/ at the end of the day just spits out a json for you. You can directly copy the entries in `Thor.json` and `Evelyn.json` into character.ai here: https://beta.character.ai/editing.

**Comment by mbchang** [comment]
Closing this issue. Please reopen if this doesn't fix the issue.

**Comment by evangineer** [comment]
Thanks.


I've decided that I'm going to adapt a copy of my roleplaying discord bot to work with this format.

https://github.com/evangineer/alpaca-roleplay-discordbot/tree/1-add-support-for-quantized-ggml-based-models-using-ctransformers
